version: '3.8'

services:
  web-api:
    build: .
    command: gunicorn main.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - notaminda

volumes:
  static_volume:

networks:
  notaminda:
    driver: bridge